-- Run this query in your Supabase SQL Editor to create the waitlist table

create table if not exists waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  sport text not null,
  phone text
);

-- Enable Row Level Security (RLS)
alter table waitlist enable row level security;

-- Create a policy that allows anyone to insert data (since it's a public waitlist form)
create policy "Enable insert for everyone" on waitlist for insert with check (true);

-- Create a policy that restricts reading data to service role only (so users can't see other people's data)
create policy "Enable read access for service role only" on waitlist for select using (auth.role() = 'service_role');
